name: jualbeli_buku_bekas
description: "Aplikasi Jual Beli Buku Bekas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0 
  url_launcher: ^6.3.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  supabase_flutter: ^2.12.0
  timeago: ^3.6.1
  audioplayers: ^6.0.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: "^1.1.0"

  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/splash.png
    - assets/sound/notif.wav
    - assets/sound/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"